import {loadStore,saveStore,emptyStore} from './db.js';
import {LocalOnlySyncAdapter} from './sync-adapter.js';

const BANK_SCHEMA='unisgiunglalab.quizlab.bank';
const BACKUP_SCHEMA='unisgiunglalab.quizlab.backup';
const sync=new LocalOnlySyncAdapter();
const app=document.getElementById('app');
const picker=document.getElementById('filePicker');
let store=emptyStore();
let route={name:'home',courseId:null};
let session=null;
let toastTimer=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').replace(/\s+/g,' ').trim();
const now=()=>new Date().toISOString();
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;};
const qbank=c=>[...(c?.officialBank||[]),...(c?.aiBank||[])];

function emptyCourse(subject=''){return {subject:norm(subject),officialBank:[],aiBank:[],topicMap:null,aiWorkflow:{},attempts:[],exams:[],marked:[],pendingReview:[],historicalWrong:[],createdAt:now(),updatedAt:now()};}
function shape(c){const x={...emptyCourse(c?.subject||''),...(c||{})};for(const k of ['officialBank','aiBank','attempts','exams','marked','pendingReview','historicalWrong'])if(!Array.isArray(x[k]))x[k]=[];return x;}
function course(id=route.courseId){return id&&store.courses[id]?shape(store.courses[id]):null;}
function saveCourse(id,c){c.updatedAt=now();store.courses[id]=c;return saveStore(store);}
function latestMap(c){const m=new Map();for(const a of c.attempts||[]){const p=m.get(a.questionId);if(!p||String(a.at)>=String(p.at))m.set(a.questionId,a);}return m;}
function metrics(c){const b=qbank(c),ids=new Set(b.map(q=>q.id)),latest=[...latestMap(c).values()].filter(a=>ids.has(a.questionId)),ok=latest.filter(a=>a.correct).length;return {total:b.length,official:c.officialBank.length,ai:c.aiBank.length,attempted:latest.length,correct:ok,coverage:b.length?latest.length/b.length:0,accuracy:latest.length?ok/latest.length:0,pending:c.pendingReview.length,marked:c.marked.length};}
function pct(v){return (v*100).toFixed(1).replace('.',',')+'%';}
function toast(s){clearTimeout(toastTimer);document.querySelector('.toast')?.remove();const d=document.createElement('div');d.className='toast';d.textContent=s;document.body.appendChild(d);toastTimer=setTimeout(()=>d.remove(),2600);}
function download(name,obj){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function fileName(s){return norm(s).replace(/[\\/:*?"<>|]+/g,'_').replace(/\s+/g,'_')||'QuizLab';}

function top(title,sub,back){return '<header class="topbar"><div class="topbar-row">'+(back?'<button class="icon-btn" data-action="back">←</button>':'')+'<div class="brand">'+esc(title)+'<small>'+esc(sub||'')+'</small></div><div class="spacer"></div><div class="sync">● locale</div></div></header>';}
function page(body,title='QuizLab Mobile DEV',sub='offline-first',back=false){app.innerHTML='<div>'+top(title,sub,back)+'<main class="main">'+body+'</main></div>';}
function setRoute(name,courseId=route.courseId){route={name,courseId};session=null;render();}

function home(){
 const rows=Object.entries(store.courses||{}).map(([id,c])=>[id,shape(c)]).filter(([,c])=>qbank(c).length||c.attempts.length).sort((a,b)=>a[1].subject.localeCompare(b[1].subject));
 let html='<div class="stack"><section class="card hero"><div class="eyebrow">DEV separata dalla stable</div><h1>Le mie materie</h1><p class="subtle">Ogni materia è separata tramite <strong>courseId</strong>. Puoi importarne quante vuoi.</p><div class="actions"><button class="btn" data-action="import">📥 Importa materia / backup</button><button class="btn secondary" data-action="backup" '+(rows.length?'':'disabled')+'>💾 Backup mobile</button></div></section>';
 if(!rows.length)html+='<section class="card empty"><strong>Nessuna materia.</strong><p>Importa il JSON “banca COMPLETA” esportato dal desktop.</p></section>';
 for(const [id,c] of rows){const m=metrics(c);html+='<section class="card"><div class="eyebrow">Materia</div><div class="subject-name">'+esc(c.subject||id)+'</div><div class="pill-row"><span class="pill off">'+m.official+' ufficiali</span><span class="pill ai">'+m.ai+' AI</span><span class="pill">'+m.attempted+' affrontate</span></div><div class="stats"><div class="stat"><span>Copertura</span><strong>'+pct(m.coverage)+'</strong></div><div class="stat"><span>Accuratezza</span><strong>'+pct(m.accuracy)+'</strong></div></div><div class="actions"><button class="btn" data-action="open" data-id="'+esc(id)+'">Apri</button><button class="btn secondary" data-action="export" data-id="'+esc(id)+'">Esporta</button></div></section>';}
 html+='<section class="card"><h3 class="section-title">Sincronizzazione</h3><p class="subtle">Per ora questa DEV lavora solo in locale. Il cloud verrà aggiunto dopo, senza toccare la stable.</p></section></div>';
 page(html);
}

function dashboard(){const c=course();if(!c)return setRoute('home',null);const m=metrics(c);page('<div class="stack"><section class="card hero"><div class="eyebrow">'+esc(route.courseId)+'</div><h1>'+esc(c.subject)+'</h1><div class="pill-row"><span class="pill off">'+m.official+' ufficiali</span><span class="pill ai">'+m.ai+' AI</span><span class="pill">'+m.total+' totali</span></div><div class="stats"><div class="stat"><span>Copertura</span><strong>'+pct(m.coverage)+'</strong></div><div class="stat"><span>Accuratezza</span><strong>'+pct(m.accuracy)+'</strong></div><div class="stat"><span>Da recuperare</span><strong>'+m.pending+'</strong></div><div class="stat"><span>Segnate</span><strong>'+m.marked+'</strong></div></div></section><section class="grid"><button class="card btn secondary" data-action="training">🎯 Allenamento</button><button class="card btn secondary" data-action="review" data-kind="pending">🔁 Da recuperare</button><button class="card btn secondary" data-action="review" data-kind="marked">⭐ Segnate</button><button class="card btn secondary" data-action="search">🔎 Cerca banca</button></section><section class="card"><div class="actions"><button class="btn secondary" data-action="export" data-id="'+esc(route.courseId)+'">Esporta materia</button><button class="btn secondary" data-action="import">Importa aggiornamento</button></div></section></div>',c.subject,'Dashboard',true);}

function training(){const c=course(),chs=uniq(qbank(c).map(q=>Number(q.chapter)).filter(Boolean)).sort((a,b)=>a-b);page('<section class="card"><h2 class="section-title">Nuovo allenamento</h2><form id="trainForm"><label>Origine<select id="source"><option value="mixed">Ufficiali + AI</option><option value="official">Solo ufficiali</option><option value="ai">Solo AI</option></select></label><label>Capitolo<select id="chapter"><option value="all">Tutta la materia</option>'+chs.map(x=>'<option value="'+x+'">Capitolo '+x+'</option>').join('')+'</select></label><label>Numero domande<select id="amount"><option>10</option><option>20</option><option selected>30</option><option>50</option><option value="all">Tutte</option></select></label><button type="button" class="btn" data-action="start-training">Inizia</button></form></section>',c.subject,'Allenamento',true);}

function filtered(c,source,chapter){return qbank(c).filter(q=>(source==='mixed'||q.source===source)&&(chapter==='all'||Number(q.chapter)===Number(chapter)));}
function startSession(questions,title,mode='training'){if(!questions.length){toast('Nessuna domanda disponibile');return;}session={questions:[...questions],index:0,answers:{},title,mode,startedAt:Date.now()};route.name='session';render();}
function current(){return session?.questions?.[session.index]||null;}
function sessionView(){const c=course(),q=current();if(!q)return setRoute('dashboard');const a=session.answers[q.id]||{},feedback=!!a.confirmed,mark=(c.marked||[]).includes(q.id);let html='<div class="stack"><section class="card"><div class="toolbar"><span class="pill">'+(session.index+1)+' / '+session.questions.length+'</span><span class="pill '+(q.source==='official'?'off':'ai')+'">'+(q.source==='official'?'Ufficiale':'AI')+'</span><span class="pill">Cap. '+q.chapter+'</span><button class="btn ghost" data-action="mark">'+(mark?'★ Segnata':'☆ Segna')+'</button></div><div class="progress"><span style="width:'+(((session.index+1)/session.questions.length)*100)+'%"></span></div><div class="question">'+esc(q.text)+'</div>';
 for(const o of q.options||[]){let cl='option';if(a.selected===o.letter)cl+=' selected';if(feedback&&o.letter===q.correct)cl+=' correct';if(feedback&&a.selected===o.letter&&a.selected!==q.correct)cl+=' wrong';html+='<button class="'+cl+'" data-action="answer" data-letter="'+esc(o.letter)+'" '+(feedback?'disabled':'')+'><span class="letter">'+esc(o.letter)+'</span><span>'+esc(o.text)+'</span></button>';}
 if(feedback){html+='<div class="feedback '+(a.correct?'ok':'bad')+'"><strong>'+(a.correct?'✓ Corretta':'✕ Errata · corretta '+esc(q.correct))+'</strong>'+(q.explanation?'<p>'+esc(q.explanation)+'</p>':'')+(q.reference?'<p class="muted"><strong>Fonte:</strong> '+esc(q.reference)+'</p>':'')+'</div>';}
 html+='<div class="actions">'+(!feedback?'<button class="btn" data-action="confirm" '+(a.selected?'':'disabled')+'>Conferma</button>':'<button class="btn" data-action="next">'+(session.index===session.questions.length-1?'Risultati':'Avanti →')+'</button>')+'</div></section></div>';page(html,c.subject,session.title,true);}

async function confirmAnswer(){const c=course(),q=current(),a=session.answers[q.id];if(!a?.selected)return;const correct=a.selected===q.correct;a.confirmed=true;a.correct=correct;a.at=now();c.attempts.push({questionId:q.id,chapter:q.chapter,source:q.source,difficulty:q.difficulty,correct,answer:a.selected,at:a.at});if(!correct){c.pendingReview=uniq([...c.pendingReview,q.id]);c.historicalWrong=uniq([...c.historicalWrong,q.id]);}else if(session.mode==='review'){c.pendingReview=c.pendingReview.filter(id=>id!==q.id);}await saveCourse(route.courseId,c);render();}
function nextQuestion(){if(session.index<session.questions.length-1){session.index++;render();}else{route.name='results';render();}}
function results(){const done=Object.entries(session.answers).filter(([,a])=>a.confirmed),ok=done.filter(([,a])=>a.correct).length,total=done.length;page('<section class="card hero"><div class="eyebrow">Sessione completata</div><h1>'+ok+' / '+total+'</h1><p>'+pct(total?ok/total:0)+' corrette</p><div class="actions"><button class="btn" data-action="dashboard">Torna alla materia</button><button class="btn secondary" data-action="retry-wrong">Ripassa gli errori</button></div></section>',course().subject,'Risultati',true);}

function review(kind){const c=course(),by=new Map(qbank(c).map(q=>[q.id,q])),ids=kind==='marked'?c.marked:c.pendingReview,qs=ids.map(id=>by.get(id)).filter(Boolean);startSession(qs,kind==='marked'?'Domande segnate':'Da recuperare','review');}

function searchPage(){const c=course();page('<div class="stack"><section class="card"><h2 class="section-title">Cerca nella banca</h2><label>Testo<input id="searchInput" placeholder="Domanda, risposta, spiegazione..."></label><div class="row"><label>Origine<select id="searchSource"><option value="mixed">Tutte</option><option value="official">Ufficiali</option><option value="ai">AI</option></select></label><label>Capitolo<input id="searchChapter" inputmode="numeric" placeholder="tutti"></label></div></section><section class="card" id="searchResults"><div class="empty">Scrivi almeno 2 caratteri.</div></section></div>',c.subject,'Esplora banca',true);setTimeout(()=>{document.getElementById('searchInput')?.addEventListener('input',updateSearch);document.getElementById('searchSource')?.addEventListener('change',updateSearch);document.getElementById('searchChapter')?.addEventListener('input',updateSearch);},0);}
function searchMatches(){const c=course(),t=norm(document.getElementById('searchInput')?.value).toLowerCase(),src=document.getElementById('searchSource')?.value||'mixed',ch=norm(document.getElementById('searchChapter')?.value);if(t.length<2&&!ch&&src==='mixed')return[];return qbank(c).filter(q=>{if(src!=='mixed'&&q.source!==src)return false;if(ch&&Number(q.chapter)!==Number(ch))return false;const hay=[q.text,q.explanation,q.reference,...(q.options||[]).map(o=>o.text)].join(' ').toLowerCase();return !t||hay.includes(t);});}
function updateSearch(){const r=searchMatches(),box=document.getElementById('searchResults');if(!box)return;box.innerHTML='<div class="toolbar"><strong>'+r.length+' risultati</strong>'+(r.length?'<button class="btn secondary" data-action="train-search">Allena risultati</button>':'')+'</div>'+r.slice(0,80).map(q=>'<div class="result"><div class="result-title">'+esc(q.text)+'</div><div class="result-meta">Cap. '+q.chapter+' · '+(q.source==='official'?'Ufficiale':'AI')+'</div><button class="btn ghost" data-action="open-question" data-qid="'+esc(q.id)+'">Apri</button></div>').join('');}

function normalizeQuestion(raw,source){if(!raw||typeof raw!=='object')return null;const options=(raw.options||[]).map((o,i)=>({letter:norm(o?.letter||['A','B','C','D'][i]).toUpperCase(),optionId:norm(o?.optionId||o?.id||('opt_'+(i+1))),text:norm(o?.text??o)})).filter(o=>/^[A-D]$/.test(o.letter)&&o.text);let correct=norm(raw.correct||raw.correctAnswer).toUpperCase();const coi=norm(raw.correctOptionId||raw.correct_option_id);if(coi){const m=options.find(o=>o.optionId===coi);if(m)correct=m.letter;}const chapter=Number(raw.chapter||raw.chapterNumber||0),text=norm(raw.text||raw.question);if(!raw.id||!chapter||!text||options.length!==4||!/^[A-D]$/.test(correct))return null;return {...raw,id:norm(raw.id),source,chapter,text,options,correct,correctOptionId:coi||options.find(o=>o.letter===correct)?.optionId||'',explanation:norm(raw.explanation||raw.spiegazione),reference:norm(raw.reference||raw.fonte||''),difficulty:['easy','medium','hard'].includes(String(raw.difficulty||'').toLowerCase())?String(raw.difficulty).toLowerCase():'medium'};}
function mergeById(oldRows,newRows){const m=new Map((oldRows||[]).map(q=>[q.id,q]));for(const q of newRows)m.set(q.id,{...(m.get(q.id)||{}),...q});return [...m.values()];}
async function importPack(p){if(!p||typeof p!=='object')throw new Error('JSON non valido');if(p.schema===BACKUP_SCHEMA){if(!p.store?.courses)throw new Error('Backup non valido');store=p.store;for(const [id,c] of Object.entries(store.courses))store.courses[id]=shape(c);await saveStore(store);return 'Backup ripristinato';}if(p.schema!==BANK_SCHEMA)throw new Error('Serve una Banca QuizLab COMPLETA o un Backup QuizLab.');const id=norm(p.course?.courseId),subject=norm(p.course?.subject||id);if(!id)throw new Error('Manca course.courseId');const off=(p.officialBank||[]).map(q=>normalizeQuestion(q,'official')).filter(Boolean),ai=(p.aiBank||[]).map(q=>normalizeQuestion(q,'ai')).filter(Boolean);if(!off.length&&!ai.length)throw new Error('Nessuna domanda valida');const c=shape(store.courses[id]||emptyCourse(subject));c.subject=subject;c.officialBank=mergeById(c.officialBank,off);c.aiBank=mergeById(c.aiBank,ai);if(p.topicMap)c.topicMap=p.topicMap;if(p.aiWorkflow)c.aiWorkflow={...c.aiWorkflow,...p.aiWorkflow};await saveCourse(id,c);return subject+': '+off.length+' ufficiali · '+ai.length+' AI';}
function exportCourse(id){const c=course(id);if(!c)return;download(fileName(c.subject)+'_QuizLab_banca_COMPLETA_mobile.json',{schema:BANK_SCHEMA,version:2,exportedAt:now(),course:{courseId:id,subject:c.subject},officialBank:c.officialBank,aiBank:c.aiBank,topicMap:c.topicMap,aiWorkflow:c.aiWorkflow});}
function backup(){download('QuizLab_Mobile_BACKUP_'+new Date().toISOString().slice(0,10)+'.json',{schema:BACKUP_SCHEMA,version:1,exportedAt:now(),store});}

function render(){if(route.name==='home')home();else if(route.name==='dashboard')dashboard();else if(route.name==='training')training();else if(route.name==='session')sessionView();else if(route.name==='results')results();else if(route.name==='search')searchPage();else home();}

app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='back'){if(route.name==='dashboard')setRoute('home',null);else if(route.name==='session'){if(confirm('Uscire dalla sessione?'))setRoute('dashboard');}else setRoute('dashboard');return;}if(a==='import'){picker.value='';picker.click();return;}if(a==='backup'){backup();return;}if(a==='open'){setRoute('dashboard',b.dataset.id);return;}if(a==='export'){exportCourse(b.dataset.id||route.courseId);return;}if(a==='training'){setRoute('training');return;}if(a==='search'){setRoute('search');return;}if(a==='review'){review(b.dataset.kind);return;}if(a==='start-training'){const c=course(),src=document.getElementById('source').value,ch=document.getElementById('chapter').value,raw=document.getElementById('amount').value,pool=shuffle(filtered(c,src,ch)),n=raw==='all'?pool.length:Math.min(Number(raw),pool.length);startSession(pool.slice(0,n),ch==='all'?'Materia completa':'Capitolo '+ch);return;}if(a==='answer'){const q=current();if(!q)return;session.answers[q.id]={...(session.answers[q.id]||{}),selected:b.dataset.letter};render();return;}if(a==='confirm'){await confirmAnswer();return;}if(a==='next'){nextQuestion();return;}if(a==='mark'){const c=course(),q=current(),s=new Set(c.marked);s.has(q.id)?s.delete(q.id):s.add(q.id);c.marked=[...s];await saveCourse(route.courseId,c);render();return;}if(a==='dashboard'){setRoute('dashboard');return;}if(a==='retry-wrong'){const c=course(),by=new Map(qbank(c).map(q=>[q.id,q])),ids=Object.entries(session.answers).filter(([,v])=>v.confirmed&&!v.correct).map(([id])=>id),qs=ids.map(id=>by.get(id)).filter(Boolean);startSession(qs,'Errori sessione','review');return;}if(a==='open-question'){const q=qbank(course()).find(x=>x.id===b.dataset.qid);if(q)startSession([q],'Domanda','study');return;}if(a==='train-search'){startSession(shuffle(searchMatches()),'Risultati ricerca');return;}});

picker.addEventListener('change',async()=>{const f=picker.files?.[0];if(!f)return;try{const msg=await importPack(JSON.parse(await f.text()));toast('Importazione OK · '+msg);render();}catch(e){alert('Importazione non riuscita:\n'+(e?.message||e));}});

async function init(){store=await loadStore();if(!store.courses||typeof store.courses!=='object')store=emptyStore();for(const [id,c] of Object.entries(store.courses))store.courses[id]=shape(c);await sync.start();render();if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./service-worker.js');}catch(e){console.warn(e);}}
init().catch(e=>{app.innerHTML='<main class="main"><section class="card"><h2>Errore avvio</h2><p>'+esc(e?.message||e)+'</p></section></main>';});
